### PR TITLE
Minor fixes and improvements to use of EWW

### LINKED ISSUE #368: Conflict when sending Ether with different wallets
## Description

This is most likely related to the use of `purser` and/or `EthersWrappedWallet` alongside/in the latest version of the `colony-js-client` package.

When using the `colonyClient.adapter.wallet.send` method with `purser` and the `getNetworkClient` method, the following assertion error occurs if the amount is not a string type:

```
Error: Assertion failed
    at assert (/Users/Admin/Workspace/projects/colony/colonyStarter/node_modules/bn.js/lib/bn.js:6:21)
    at BN._initArray (/Users/Admin/Workspace/projects/colony/colonyStarter/node_modules/bn.js/lib/bn.js:145:5)
    at BN.init [as _init] (/Users/Admin/Workspace/projects/colony/colonyStarter/node_modules/bn.js/lib/bn.js:82:19)
    at new BN (/Users/Admin/Workspace/projects/colony/colonyStarter/node_modules/bn.js/lib/bn.js:39:12)
    at EthersWrappedWallet._callee3$ (/Users/Admin/Workspace/projects/colony/colonyStarter/node_modules/@colony/colony-js-client/lib/lib/EthersWrappedWallet/index.js:178:32)
...
```

When using the traditional `ethers` wallet, the following error occurs if the amount is a string type:

```
{ Error: invalid hexlify value
    at Object.throwError (/Users/Admin/Workspace/projects/colony/colonyStarter/node_modules/ethers/utils/errors.js:74:17)
    at Object.hexlify (/Users/Admin/Workspace/projects/colony/colonyStarter/node_modules/ethers/utils/convert.js:167:12)
    at Wallet.sendTransaction (/Users/Admin/Workspace/projects/colony/colonyStarter/node_modules/ethers/wallet/wallet.js:279:23)
    at Wallet.send (/Users/Admin/Workspace/projects/colony/colonyStarter/node_modules/ethers/wallet/wallet.js:306:17)
    at sendEther (/Users/Admin/Workspace/projects/colony/colonyStarter/packages/colony-starter-basic/src/examples/sendEther.js:14:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  reason: 'invalid hexlify value',
  code: { arg: 'value', value: '3000000000000000000' } }
```

### PR DESCRIPTION
**Pull request by ryanchristo**
## Description

This pull request fixes the following issues:

- [x] I can still use an `ethers` wallet when using the `getNetworkClient` method
- [x] `adapter.wallet.wallet.address` should be `adapter.wallet.address`
- [x] I don't need to set the `gasLimit` for methods when using a purser wallet
- [x] `adapter.wallet.send(address, amount)` should accept a big number for `amount`

Resolves #368

### CODE REVIEW

File: packages/colony-js-client/src/lib/EthersWrappedWallet/index.js [hunk 1]
```diff
@@ -15,11 +15,12 @@ import type {
 } from './types';
 
 export default class EthersWrappedWallet {
+  address: string;
   wallet: GenericWallet;
-
   provider: *;
 
   constructor(wallet: *, provider: *) {
+    this.address = wallet.address;
```
Comment (sprusr) [inline packages/colony-js-client/src/lib/EthersWrappedWallet/index.js]: I think it would be nicer to have a getter:

```js
get address() {
  return this.wallet.address;
}
```

File: packages/colony-js-client/src/lib/EthersWrappedWallet/index.js [hunk 2]
```diff
@@ -46,11 +47,15 @@ export default class EthersWrappedWallet {
     const signOptions = {
       chainId: chainId || this.provider.chainId,
       data,
-      gasLimit: gasLimit ? new BigNumber(gasLimit) : await this.estimateGas(tx),
+      // If no gas limit is provided, we need to get the estimate and multiply
+      // it by 1.1 (an amount that will prevent the transaction from failing)
+      gasLimit: gasLimit
+        ? new BigNumber(gasLimit)
+        : new BigNumber((await this.estimateGas(tx)).toNumber() * 1.1),
```
Comment (sprusr) [inline packages/colony-js-client/src/lib/EthersWrappedWallet/index.js]: Can this be done with BN's `.mul(1.1)`, or does that only accept integers? In that case maybe `.mul(11).div(10)`?

File: packages/colony-js-client/src/lib/EthersWrappedWallet/index.js (hunk 1 above)
Comment (ryanchristo) [reply packages/colony-js-client/src/lib/EthersWrappedWallet/index.js]: 👍

File: packages/colony-js-client/src/lib/EthersWrappedWallet/index.js (hunk 2 above)
Comment (ryanchristo) [reply packages/colony-js-client/src/lib/EthersWrappedWallet/index.js]: Yea, `.mul(1.1)` is not possible because you cannot multiply by decimals. I have changed it to what you suggested but it looks like this:

```
      gasLimit: gasLimit
        ? new BigNumber(gasLimit)
        : (await this.estimateGas(tx))
            .mul(new BigNumber('11'))
            .div(new BigNumber('10')),
```
